# -*- coding: utf-8 -*-
"""Project 2: Guess the Number Game Python Project (computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmUkOTSyBS-qnv5zm5IjfIu2zwzUF5Ym

## Project 02 : Guess the Number game (computer)
This project is a simple "Guess the Number" game implemented in Python. The game involves the computer randomly selecting a number within a specified range, and the player trying to guess the number. The computer provides feedback on whether the guess is too high, too low, or correct.
"""

import random

def guess_the_number():
    """
    Guess the Number Game

    In this game, the computer randomly selects a number within a specified range, and the player tries to guess the number.
    The computer provides feedback on whether the guess is too high, too low, or correct.

    This project helps beginners learn:
    - How to work with Python's random module.
    - How to build functions.
    - How to use while loops and conditionals.
    - How to get user input.
    """
    print("Welcome to the 'Guess the Number' game!")
    print("I'm thinking of a number between 1 and 100.")

    # Generate a random number between 1 and 100
    number_to_guess = random.randint(1, 100)

    # Initialize the number of attempts
    attempts = 0

    while True:
        # Get the user's guess
        guess = input("Enter your guess: ")

        # Try to convert the user's input to an integer
        try:
            guess = int(guess)
        except ValueError:
            print("Please enter a valid number.")
            continue

        # Increment the number of attempts
        attempts += 1

        # Provide feedback based on the user's guess
        if guess < number_to_guess:
            print("Too low! Try again.")
        elif guess > number_to_guess:
            print("Too high! Try again.")
        else:
            print(f"Congratulations! You guessed the number {number_to_guess} in {attempts} attempts.")
            break

if __name__ == "__main__":
    guess_the_number()



