# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvJs6udgTTETZlx1jCj3yHUFZNB-BXUn
"""

import random

def basic_madlib():
    adj = input("Adjective: ")
    verb1 = input("Verb: ")
    verb2 = input("Verb: ")
    famous_person = input("Famous person: ")

    madlib = f"Computer programming is so {adj}! It makes me so excited all the time because \
    I love to {verb1}. Stay hydrated and {verb2} like you are {famous_person}!"

    print(madlib)

def code_madlib():
    adj = input("Adjective: ")
    verb1 = input("Verb: ")
    verb2 = input("Verb: ")
    famous_person = input("Famous person: ")

    madlib = f"Computer programming is so {adj}! It makes me so excited all the time because \
    I love to {verb1}. Stay hydrated and {verb2} like you are {famous_person}!"

    print(madlib)

def hp_madlib():
    adj = input("Adjective: ")
    noun = input("Noun: ")
    verb = input("Verb: ")
    place = input("Place: ")

    madlib = f"It was a {adj} day at Hogwarts. Harry and his friends were {verb} in the {place} when they found a mysterious {noun}."

    print(madlib)

def hunger_games_madlib():
    adj = input("Adjective: ")
    noun = input("Noun: ")
    past_verb = input("Past tense verb: ")
    place = input("Place: ")

    madlib = f"In the {adj} world of Panem, a young tribute found a {noun} that changed everything. They {past_verb} through the {place} to survive."

    print(madlib)

def zombie_madlib():
    adj = input("Adjective: ")
    noun = input("Noun: ")
    verb = input("Verb: ")
    place = input("Place: ")

    madlib = f"During the {adj} zombie apocalypse, survivors needed to {verb} quickly. They found a safe house in the {place} with enough {noun} to last for weeks."

    print(madlib)

def random_madlib():
    madlibs = [code_madlib, hp_madlib, hunger_games_madlib, zombie_madlib]
    m = random.choice(madlibs)
    m()

if __name__ == "__main__":
    print("Select a project to run:")
    print("1. Basic Madlibs")
    print("2. Madlibs Randomizer")

    choice = input("Enter the number of the project you want to run: ")

    if choice == "1":
        print("Running Project 01: Basic Madlibs")
        basic_madlib()
    elif choice == "2":
        print("Running Project 02: Madlibs Randomizer")
        random_madlib()
    else:
        print("Invalid choice. Please run the script again and select either 1 or 2.")