# -*- coding: utf-8 -*-
"""Project 4 Rock, paper, scissors Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKi_L7KKKLVYnD0SVW2oUHzvP5HmESIy

# Project 4 Rock, paper, scissors Python Project
In this game, the user will play "Rock, Paper, Scissors" against the computer. The computer will randomly select one of the options, and the user will input their choice. The game will then determine the winner based on the rules of "Rock, Paper, Scissors".
"""

import random

def play():
    """
    Rock, Paper, Scissors Game

    In this game, the user plays rock, paper, scissors against the computer.
    The computer randomly selects one of the options, and the user inputs their choice.
    The game determines the winner based on the rules of rock, paper, scissors.

    This project helps beginners learn:
    - How to use random.choice() to make random selections.
    - How to build functions.
    - How to use if statements to handle conditions.
    - How to get user input.
    """
    options = ["rock", "paper", "scissors"]
    computer_choice = random.choice(options)
    user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()

    if user_choice not in options:
        print("Invalid choice. Please choose rock, paper, or scissors.")
        return

    print(f"Computer chose: {computer_choice}")
    print(f"You chose: {user_choice}")

    if user_choice == computer_choice:
        print("It's a tie!")
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        print("You win!")
    else:
        print("You lose!")

if __name__ == "__main__":
    play()

