# -*- coding: utf-8 -*-
"""Project 7: Password Generator Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1by58w00eiOwTCDIqKJI4nM61ohzj8k1s

# Project 7: Password Generator Python Project
In this project, you will create a password generator that:

- Asks the user for the number of passwords they want to generate.
- Asks the user for the length of each password.
- Generates random passwords using a mix of letters, digits, and special characters.
- Outputs the generated passwords.
"""

import random
import string

def generate_password(length):
    """
    Generate a random password of a given length.

    The password will include a mix of uppercase letters, lowercase letters, digits, and special characters.
    """
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    return password

def main():
    """
    Main function to generate multiple passwords based on user input.
    """
    try:
        num_passwords = int(input("Enter the number of passwords to generate: "))
        password_length = int(input("Enter the length of each password: "))

        print("\nGenerated Passwords:")
        for _ in range(num_passwords):
            print(generate_password(password_length))

    except ValueError:
        print("Please enter valid numbers for the number of passwords and their lengths.")

if __name__ == "__main__":
    main()

