# -*- coding: utf-8 -*-
"""Project 5 Hangman Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k98abyiHZukcf6KcsgA19NlhZ7_TXUKx

# Project 5: Hangman Python Project
In this project, you will create a simple Hangman game where the player has to guess a hidden word one letter at a time. The player has a limited number of incorrect guesses before the game is over.
"""

import random
import string

def get_valid_word(words):
    word = random.choice(words)  # randomly chooses a word from the list
    while '-' in word or ' ' in word:
        word = random.choice(words)
    return word.upper()

def hangman():
    words = ["PYTHON", "DEVELOPER", "HANGMAN", "DEBUGGING", "FUNCTION", "VARIABLE", "DICTIONARY", "LIST", "TUPLE"]
    word = get_valid_word(words)
    word_letters = set(word)  # letters in the word
    alphabet = set(string.ascii_uppercase)
    used_letters = set()  # what the user has guessed

    lives = 6

    # getting user input
    while len(word_letters) > 0 and lives > 0:
        # letters used
        print('You have', lives, 'lives left and you have used these letters: ', ' '.join(used_letters))

        # what current word is (i.e. W - R D)
        word_list = [letter if letter in used_letters else '-' for letter in word]
        print('Current word: ', ' '.join(word_list))

        user_letter = input('Guess a letter: ').upper()
        if user_letter in alphabet - used_letters:
            used_letters.add(user_letter)
            if user_letter in word_letters:
                word_letters.remove(user_letter)
            else:
                lives -= 1  # takes away a life if wrong
                print(f'\nYour letter, {user_letter} is not in the word.')

        elif user_letter in used_letters:
            print('\nYou have already used that letter. Guess another letter.')

        else:
            print('\nThat is not a valid letter.')

    # gets here when len(word_letters) == 0 or when lives == 0
    if lives == 0:
        print(f'Sorry, you died. The word was {word}.')
    else:
        print(f'YAY! You guessed the word {word}!!')

if __name__ == "__main__":
    hangman()

