# -*- coding: utf-8 -*-
"""Project 3 Guess the Number Game Python Project (user).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suOasYMgHXKIQdgCyzrhX2rkLTj2AkTd

# Project 03:  Guess the Number Game Python Project (user).
In this game, the user thinks of a number within a specified range, and the computer tries to guess the number. The user provides feedback on whether the guess is too high, too low, or correct.
"""

import random

def computer_guess(x):
    """
    Computer Guesses the Number Game

    In this game, the user thinks of a number within a specified range, and the computer tries to guess the number.
    The user provides feedback on whether the guess is too high, too low, or correct.

    This project helps beginners learn:
    - How to work with Python's random module.
    - How to build functions.
    - How to use while loops and conditionals.
    - How to get user input.
    """
    low = 1
    high = x
    feedback = ''
    attempts = 0

    print(f"Think of a number between {low} and {high}. The computer will try to guess it!")

    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low  # or high, since low == high
        attempts += 1

        feedback = input(f"Is {guess} too high (H), too low (L), or correct (C)? ").lower()

        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
        elif feedback == 'c':
            print(f"Yay! The computer guessed your number, {guess}, in {attempts} attempts!")
        else:
            print("Please enter 'H', 'L', or 'C'.")

if __name__ == "__main__":
    computer_guess(100)

